ydRSoft.Web/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ydRSoft.BL;
using ydRSoft.Model;
using ydRSoft.ViewModel;
namespace ydRSoft.Web.Controllers
{
    public class CompraController : Controller
    {
        #region Solicitud Compra
        
        public ActionResult Solicitud()
        {

            TipoBL bl = new TipoBL();
            ViewBag.TipoAlma = new SelectList(bl.ListaTipoAlma(), "ID", "Nombre");            
            ViewBag.Sede = new SelectList(bl.ListaSede(), "ID", "Nombre");
            

            return View();
        }

        [HttpPost]
        public ActionResult AddCompraSol(CompraSolModel mSol) {

            CompraBL bl = new CompraBL();

            var resultado = bl.AddSolicitud(mSol);

            TempData["Error"] = resultado.Mensaje;
            if (!resultado.Error) {
                TempData["Mensaje"] = resultado.Mensaje;
            }
            TipoBL tbl = new TipoBL();
            ViewBag.ListaDetalle = bl.ListaDetSol(mSol.ID_Empl);
            ViewBag.TipoAlma = new SelectList(tbl.ListaTipoAlma(), "ID", "Nombre");
            return PartialView("_ListaDetalleSol");

        }

        [HttpPost]
        public ActionResult EditCompraSol(CompraSolModel mSol)
        {
            CompraBL bl = new CompraBL();
            var resultado = bl.EditSolicitud(mSol);

            TempData["Error"] = resultado.Mensaje;
            if (!resultado.Error)
            {
                TempData["Mensaje"] = resultado.Mensaje;
            }

            TipoBL tbl = new TipoBL();
            ViewBag.ListaDetalle = bl.ListaDetSol(mSol.ID_Empl);
            ViewBag.TipoAlma = new SelectList(tbl.ListaTipoAlma(), "ID", "Nombre");
            return PartialView("_ListaDetalleSol");
        }

        public ActionResult ListaDetSol()
        {
            EmpleadoModel objEmpleado = (EmpleadoModel)Session["objEmpleado"];
            if (objEmpleado == null)
                objEmpleado = new EmpleadoModel();

            CompraBL bl = new CompraBL();            
            TipoBL tbl = new TipoBL();
            ViewBag.ListaDetalle = bl.ListaDetSol(objEmpleado.DNI);
            ViewBag.TipoAlma = new SelectList(tbl.ListaTipoAlma(), "ID", "Nombre");
            return PartialView("_ListaDetalleSol");
        }


        public ActionResult SendSol()
        {
            EmpleadoModel objEmpleado = (EmpleadoModel)Session["objEmpleado"];

            if (objEmpleado != null) {
                CompraBL bl = new CompraBL();

                bl.EnviarSolicitud(objEmpleado.DNI);
            }

            return RedirectToAction("Solicitud");
        }

        public ActionResult ListaSol()
        {
            return View();
        }

        public ActionResult getListaSol(int IdDet)
        {
            CompraBL bl = new CompraBL();

            ViewBag.ListaSol = bl.ListaSolicitud(ydR.Estado.ENVIADO);

            return PartialView("_ListaSol");
        }
        
        public ActionResult AprobarSol(int IdSol)
        {
            CompraBL bl = new CompraBL();
            EmpleadoModel objEmpleado = (EmpleadoModel)Session["objEmpleado"];

            RespuestaModel resultado = new RespuestaModel(ydR.Mensaje.DontSave);
            if (objEmpleado != null) {
                resultado = bl.OpcSolicitud(IdSol, objEmpleado.DNI, ydR.Estado.APROBADO, "");
            }

            TempData["Error"] = resultado.Mensaje;
            if (!resultado.Error)
            {
                TempData["Mensaje"] = resultado.Mensaje;
            }

            ViewBag.ListaSol = bl.ListaSolicitud(ydR.Estado.ENVIADO);
            return PartialView("_ListaSol");
        }

        public ActionResult CancelSol(int IdSol,string Obser)
        {
            CompraBL bl = new CompraBL();
            EmpleadoModel objEmpleado = (EmpleadoModel)Session["objEmpleado"];

            RespuestaModel resultado = new RespuestaModel(ydR.Mensaje.DontSave);
            if (objEmpleado != null)
            {
                resultado = bl.OpcSolicitud(IdSol, objEmpleado.DNI, ydR.Estado.RECHAZADO, Obser);
            }

            TempData["Error"] = resultado.Mensaje;
            if (!resultado.Error)
            {
                TempData["Mensaje"] = resultado.Mensaje;
            }

            ViewBag.ListaSol = bl.ListaSolicitud(ydR.Estado.ENVIADO);
            return PartialView("_ListaSol");
        }
        
        #endregion

        #region Orden Compra

        public ActionResult OrdenCompra()
        {
            TipoBL bl = new TipoBL();
            ViewBag.Moneda = new SelectList(bl.ListaMoneda(), "ID", "Nombre");
            ViewBag.Sede = new SelectList(bl.ListaSede(), "ID", "Nombre");

            return View();
        }

        public JsonResult JsonaListaSol(int ID_Tipo)
        {
            CompraBL bl = new CompraBL();
            return Json(bl.ListaAlmaSol(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AddOrden(CompraOrdModel mOrden)
        {
            CompraBL bl = new CompraBL();
            var resultado = bl.AddOrden(mOrden);   
            
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public ActionResult AddDetalle(CompraDetModel mDetalle)
        {
            CompraBL bl = new CompraBL();

            var resultado = bl.AddDetalle(mDetalle);
            TempData["Error"] = resultado.Mensaje;
            if (!resultado.Error) {
                TempData["Mensaje"] = resultado.Mensaje;
            }

            ViewBag.ListaDetalle = bl.ListaDetalle(mDetalle.ID_Cuerpo);
            return PartialView("_ListaDetalle");
        }


        [HttpPost]
        public ActionResult EditDetalle(CompraDetModel mDetalle)
        {
            CompraBL bl = new CompraBL();

            var resultado = bl.EditDetalle(mDetalle);
            TempData["Error"] = resultado.Mensaje;
            if (!resultado.Error)
            {
                TempData["Mensaje"] = resultado.Mensaje;
            }


            ViewBag.ListaDetalle = bl.ListaDetalle(mDetalle.ID_Cuerpo);
            return PartialView("_ListaDetalle");
        }

        public ActionResult DeleteDetalle(int IdDet,int IdCuerpo)
        {
            CompraBL bl = new CompraBL();
            var resultado = bl.DeleteDetalle(IdDet);
            TempData["Error"] = resultado.Mensaje;
            if (!resultado.Error)
            {
                TempData["Mensaje"] = resultado.Mensaje;
            }

            ViewBag.ListaDetalle = bl.ListaDetalle(IdCuerpo);

            return PartialView("_ListaDetalle");
        }

        public ActionResult GetDetalle(int IdCuerpo)
        {
            CompraBL bl = new CompraBL();           
            ViewBag.ListaDetalle = bl.ListaDetalle(IdCuerpo);
            return PartialView("_ListaOrden");
        }

        public ActionResult JsonSendOrd(int IdOrden) {

            CompraBL bl = new CompraBL();
            var resultado = bl.SerndOrden(IdOrden);

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ListaOrden()
        {
            CompraBL bl = new CompraBL();
            ViewBag.ListaOrden = bl.ListaOrden(ydR.Estado.ENVIADO);
            return View();
        }

        public ActionResult getListaOrden()
        {
            CompraBL bl = new CompraBL();

            ViewBag.ListaOrden = bl.ListaOrden(ydR.Estado.ENVIADO);
            return PartialView("_ListaOrden");
        }

        #endregion

        #region Guia COmpra
        public ActionResult Guia(int? Id)
        {
            if (Id.HasValue) {
                TipoBL tbl = new TipoBL();
                ViewBag.Sede = new SelectList(tbl.ListaSede(), "ID", "Nombre");
                CompraBL bl = new CompraBL();
                var vmGuia = bl.CargarGuia(Id.Value);
                if (vmGuia != null) {
                    if (vmGuia.Estado == 0) {
                        return View(vmGuia);
                    }                        
                }
            }

            return RedirectToAction("ListaOrden");
        }

       

        [HttpPost]
        public ActionResult AddGuia(CompraGuiaModel mGuia, HttpPostedFileBase fileUpload)
        {
            RespuestaModel resultado = new RespuestaModel();
            try
            {
                byte[] imagenData = null;
                
                if (fileUpload != null && fileUpload.ContentLength > 0)
                {
                    using (var imagen = new BinaryReader(fileUpload.InputStream))
                    {
                        imagenData = imagen.ReadBytes(fileUpload.ContentLength);
                    }

                    EmpleadoModel objEmpleado = (EmpleadoModel)Session["objEmpleado"];

                    mGuia.ID_Empl = objEmpleado.DNI;
                    mGuia.Img = imagenData;
                    CompraBL bl = new CompraBL();
                    resultado = bl.AddGuia(mGuia);
                }

                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
            
        }

        public ActionResult ApruebaGuia(int IdGuia)
        {
            CompraBL bl = new CompraBL();

            EmpleadoModel objEmpleado = (EmpleadoModel)Session["objEmpleado"];
            RespuestaModel resultado = new RespuestaModel();
            if (objEmpleado != null) {
                resultado = bl.AprobarGuia(IdGuia, objEmpleado.DNI);
            }

            ViewBag.vmLista = bl.ListaGuia(ydR.Estado.NUEVO);

            return PartialView("_ListaGuia");
        }
        
        public ActionResult EditGuiaDetalle(CompraDetModel mDet)
        {
            CompraBL bl = new CompraBL();
            var resultado = bl.EditDetGuia(mDet);

ydRSoft.Web/Controllers/Modulos/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ydRSoft.BL;
using ydRSoft.Model;
using ydRSoft.ViewModel;

namespace ydRSoft.Web.Controllers
{
    public class EmpleadoController : Controller
    {
        
        private List<TipoModel> ListaSexo()
        {
            try

            {
                List<TipoModel> lista = new List<TipoModel>();
                lista.Add(new TipoModel(1, "HOMBRE"));
                lista.Add(new TipoModel(2, "MUJER"));
                return lista;

            }
            catch
            {
                return null;
            }
        }

        public ActionResult Dashboard() {
            return View();
        }

        public ActionResult AddEmpleado(EmpleadoViewModel vmEmpleado)
        {
            if (Session["objEmpleado"] != null)
            {
                EmpleadoModel objEmpleado = (EmpleadoModel)Session["objEmpleado"];
                EmpleadoBL bl = new EmpleadoBL();
                ViewBag.ListaSexo = new SelectList(ListaSexo(), "ID", "Nombre");
                ViewBag.ListaCargo = new SelectList(bl.listaCargo(objEmpleado.ID_Cargo), "ID", "Nombre");
                if (vmEmpleado == null)
                    vmEmpleado = new EmpleadoViewModel();

                return View(vmEmpleado);
            }
            else {
                return RedirectToAction("Index","Home");
            }  
        }

        [HttpPost]
        public ActionResult AddEmpleado(EmpleadoViewModel vmEmpleado, int? Tipo)
        {
            if (!ModelState.IsValid) {
                TempData["Error"] = "Corrija los campos marcados !!!";
                return RedirectToAction("AddEmpleado",vmEmpleado);
            }

            EmpleadoBL bl = new EmpleadoBL();

            int IdEmpl = bl.AddEmpleado(vmEmpleado);

            if (IdEmpl <= 0)
            {
                TempData["Error"] = "Error de Conexion !!!";
                if (IdEmpl == 0)
                    TempData["Error"] = "Empleado No Guardado !!!";

                return View();
            }
            else
            {
                TempData["Mensaje"] = "Empleado Guardado";
                return RedirectToAction("AddEmpleado");
            }
        }


    }
}

ydRSoft.Web/Views/Shared/_Layout.cshtml
 
@{
    ydRSoft.Model.EmpleadoModel objEmpleado = (ydRSoft.Model.EmpleadoModel)Session["objEmpleado"];
    string vmNombre = string.Empty;
    string vmCargo = string.Empty;
    string vmDNI = string.Empty;
    string vmCorreo = string.Empty;
    int IdCargo = 0;
    int vmSexo = 1;
    if (objEmpleado != null)
    {
        vmNombre = objEmpleado.Nombres;
        vmDNI = objEmpleado.DNI;
        vmCorreo = objEmpleado.Correo;
        IdCargo = objEmpleado.ID_Cargo;
        vmCargo = objEmpleado.Cargo;
        vmSexo = objEmpleado.ID_Sexo;
    }
    else
    {
        @*<script> window.location.href='@Url.Action("Index", "Home")'; </script>*@
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ydRSoft.ydR.Variable.EMPRESA</title>
    <link rel="icon" href="~/paw.ico" />
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/font-awesome/css/font-awesome.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/css/animate.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/css/style.css")" rel="stylesheet">
    <link href="@Url.Content("~/Content/css/styleyader.css" )" rel="stylesheet">

    @Styles.Render("~/Content/css");

</head>
<body class="">
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            @if (vmSexo == 1)
                            {<img alt="image" class="rounded-circle" src="~/Content/img/avatar/hombre.png" width="48" />}
                            else
                            { <img alt="image" class="rounded-circle" src="~/Content/img/avatar/mujer.png" width="48" />}

                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="block m-t-xs font-bold">@vmNombre</span>
                                <span class="text-muted text-xs block">@vmCargo <b class="caret"></b></span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="dropdown-item" href="@Url.Action("Dashboard","Empleado")"> Mi Perfil</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Dashboard","Empleado")">Actividades</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Dashboard","Empleado")">configuracion</a></li>
                                <li class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="@Url.Action("Logout", "Home")">Cerrar Sesion</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            @ydRSoft.ydR.Variable.LOGO
                        </div>
                    </li>
                    @if (IdCargo == 9)
                    {
                        <li>
                            <a href="@Url.Action("Dashboard", "Home")"><i class="fa fa-th-large"></i> <span class="nav-label">INICIO</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("Solicitud", "Compra")"> <span class="nav-label"> &nbsp; Solicitud</span> <span class="float-left label label-primary">01</span> </a>
                        </li>
                        <li>
                            <a href="@Url.Action("ListaSol", "Compra")"> <span class="nav-label">&nbsp; Lista Sol</span><span class="float-left label label-primary">02</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("OrdenCompra", "Compra")"> <span class="nav-label">&nbsp; Orden</span><span class="float-left label label-primary">03</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("ListaOrden", "Compra")"> <span class="nav-label">&nbsp; Lista Orden</span><span class="float-left label label-primary">04</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("ListaNewGuia", "Compra")"> <span class="nav-label">&nbsp; Lista Guia</span><span class="float-left label label-primary">06</span></a>
                        </li>

                        <li>
                            <a href="@Url.Action("GuiaApro", "Compra")"> <span class="nav-label">&nbsp; Guias Aprob</span><span class="float-left label label-primary">07</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("ListaComp", "Compra")"> <span class="nav-label">&nbsp; Lista Compra</span><span class="float-left label label-primary">08</span></a>
                        </li>
                    }                    
                </ul>
            </div>
        </nav>
        <!-- Contenido  Inicio -->
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top  " role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    </div>
                    <ul class="nav navbar-top-links navbar-left">
                        <li>
                            <span class="m-r-sm text-success welcome-message"><strong> @ydRSoft.ydR.Variable.EMPRESA </strong> &nbsp; &nbsp; Te da la bienvenida</span>
                        </li>
                    </ul>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <a href="@Url.Action("Logout", "Home")">
                                <i class="fa fa-sign-out"></i> Salir
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            @RenderBody()
            @Scripts.Render("~/Content/js/jquery-3.1.1.min.js")
            @RenderSection("scripts", required: false)
            <div class="footer">
                <div class="float-right">
                    ydR <strong>CH</strong>
                </div>
                <div>
                    <strong>Copyright</strong>  &copy; @DateTime.Now.Year
                </div>
            </div>
        </div>
        <!-- Contenido  Fin -->
    </div>
    <script src="@Url.Content("~/Content/js/popper.min.js")"></script>
    <script src="@Url.Content("~/Content/js/jquery-3.1.1.min.js")"></script>
    <script src="@Url.Content("~/Content/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/js/plugins/metisMenu/jquery.metisMenu.js")"></script>
    <script src="@Url.Content("~/Content/js/plugins/slimscroll/jquery.slimscroll.min.js")"></script>
    <script src="@Url.Content("~/Content/js/bootstrap.js")"></script>
    <script src="@Url.Content("~/Content/js/inspinia.js")"></script>
    <script src="@Url.Content("~/Content/js/plugins/pace/pace.min.js")"></script>
</body>
</html>